// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Deck = (function(_super) {
    __extends(Deck, _super);

    function Deck() {
      _ref = Deck.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Deck.prototype.model = Card;

    Deck.prototype.initialize = function() {
      this.on('remove', this.checkSize, this);
      return this.add(_(_.range(1, 53)).shuffle().map(function(card) {
        return new Card({
          rank: card % 13,
          suit: card > 51 ? 3 : Math.floor(card / 13)
        });
      }));
    };

    Deck.prototype.dealPlayer = function(discard) {
      return new Hand([], this, false, discard);
    };

    Deck.prototype.dealDealer = function(discard) {
      return new Hand([this.pop().flip(), this.pop()], this, true, discard);
    };

    Deck.prototype.checkSize = function(deck) {
      if (this.length < 15) {
        return this.trigger('runningLow', this);
      }
    };

    return Deck;

  })(Backbone.Collection);

}).call(this);

/*
//@ sourceMappingURL=Deck.map
*/
