// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.DiscardPile = (function(_super) {
    __extends(DiscardPile, _super);

    function DiscardPile() {
      _ref = DiscardPile.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    DiscardPile.prototype.model = Card;

    DiscardPile.prototype.intialize = function() {};

    return DiscardPile;

  })(Backbone.Collection);

}).call(this);

/*
//@ sourceMappingURL=DiscardPile.map
*/
